<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
   <HEAD>
      <TITLE>[@title]</TITLE>
      <style>
        html, button, input, select, textarea, .pure-g [class *= "pure-u"] {
            font-family: sans-serif;
            font-weight: 100;
            letter-spacing: 0.01em;
        }

        body {
            margin: 0;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 13px;
            line-height: 18px;
            color: #333333;
        }

        .news-form input[type=text], .news-form input[type=password], .news-form input[type=email], 
        .news-form input[type=url], .news-form input[type=date], .news-form input[type=month], 
        .news-form input[type=time], .news-form input[type=datetime], .news-form input[type=datetime-local], 
        .news-form input[type=week], .news-form input[type=number], .news-form input[type=search], 
        .news-form input[type=tel], .news-form input[type=color], .news-form select, .news-form textarea {
            padding: .5em .6em;
            display: inline-block;
            border: 1px solid #ccc;
            box-shadow: inset 0 1px 3px #ddd;
            border-radius: 4px;
            vertical-align: middle;
            box-sizing: border-box;
            font-size: 15px;
        }

        .news-form input, .news-form textarea {
            margin: 5px;
        }

        .top .menu {
            display: inline;
            float: left;
        }

        .top .search {
            display: inline;
            float: right;
            padding: 15px;
        }

        .top {
            display: block;
            max-width: 1160px;
            margin: auto;
            background-color: #000;
            color: #fff;
            height: 50px;
        }

        .top a {
            color: #fff;
            text-decoration: none;
        }

        .content {
            display: block;
            clear: both;
            max-width: 1160px;
            margin: auto;
        }

        .menu ul li {
            font-family: FontAwesome;
            display: inline;
            vertical-align: middle;
            font-size: 1.3em;
            font-weight: bold;
            border-right: 1px white solid;
            border-spacing: 5px;
            padding: 5px;
        }

        .menu ul li.last {
            border: 0px;
        }

        .error404 {
            margin: auto;
            margin-top: 30px;
            text-align: center;
            font-size: 20px;
        }

        ul.news-list {
            font-size: 15px;
        }

        ul.news-list li {
            padding: 10px 5px;
        }

        .footer {
            width: 1160px;
            display: block;
            clear: both;
            padding-top: 10px;
            margin-top: 10px;
            border-top: 1px solid black;
            text-align: center;
            margin: auto;
        }

        #logo {
            display: block;
            float: left;
            height: 50px;
            width: 100px;
            text-indent: -9999em;
            overflow: hidden;
            text-decoration: none;
            background: url(http://www.bab.la/pic/logo-babla-header-small2.png) no-repeat left center scroll;
            padding: 0;
            margin: 0 10px 0 0;
            position: relative;
            left: 10px;
            top: 0px;
        }

        #news_preview {
            display: none;
        }

        a {
            text-decoration: none;  
        }

        .extra {
            margin-top: 15px;
            padding: 10px;
            background-color: #eee;
            font-size: 15px;
            color: red;
            font-weight: bold;
        }
      </style>
   </HEAD>
   <BODY>
       <div class="wrapper">
           <div class="top">
               <div class="menu">
                 <ul>
                     <li><a href="[@baseUrl]">Home</a></li>
                     <li><a href="[@baseUrl]/add/">Submit News</a></li>
                     <li class="last"><a href="[@baseUrl]/logout">Logout</a></li>
                   </ul> 
               </div>
               <div class="search">
                   <form method="GET" action="[@baseUrl]/search/">
                       <input type="text" name="query" placeholder="Search News" value="[@query]" required /> 
                       <input type="submit" name="Go">
                   </form>
               </div>   
           </div>
           <div class="content">
               <div class="[@message_class]">
                   [@message]
               </div>
                [@content]
           </div>
       </div>
   </BODY>
</HTML>
